# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReactNativeOsef' do
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.15.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/AdMob', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Database', '~> 5.15.0'
  pod 'Firebase/Functions', '~> 5.15.0'
  pod 'Firebase/DynamicLinks', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'
  # pod 'Firebase/Invites', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
  pod 'Firebase/RemoteConfig', '~> 5.15.0'
  pod 'Firebase/Storage', '~> 5.15.0'
  pod 'Firebase/Performance', '~> 5.15.0'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.9'

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTText',
    'RCTNetwork',
    'RCTSettings',
    'RCTVibration',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    'RCTLinkingIOS',
  ]

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-maps', path: '../node_modules/react-native-maps'
  pod 'react-native-google-maps', path: '../node_modules/react-native-maps'  # Unomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'


end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
