# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "a5acb138-a1a7-4db5-bde8-7199ec81570f"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build your iOS app
  build_app(
    # scheme: "YourScheme",
    export_method: "ad-hoc"
  )

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "3d89bc4e8289600510acb10d80ff7a8c8a30ea1a",
    build_secret: "56c70a96954ef051263770387e1d2e840eae0016c931d8f5653283bc805a882b"
  )
end
